export const INTUIT_ACCOUNT_ENUMS = {
  Bank: [
    "Default",
    "CashOnHand",
    "Checking",
    "MoneyMarket",
    "RentsHeldInTrust",
    "Savings",
    "TrustAccounts",
    "CashAndCashEquivalents",
    "OtherEarMarkedBankAccounts"],
  "Other Current Asset": [
    "AllowanceForBadDebts"
    , "DevelopmentCosts"
    , "EmployeeCashAdvances"
    , "OtherCurrentAssets"
    , "Inventory"
    , "Investment_MortgageRealEstateLoans"
    , "Investment_Other"
    , "Investment_TaxExemptSecurities"
    , "Investment_USGovernmentObligations"
    , "LoansToOfficers"
    , "LoansToOthers"
    , "LoansToStockholders"
    , "PrepaidExpenses"
    , "Retainage"
    , "UndepositedFunds"
    , "AssetsAvailableForSale"
    , "BalWithGovtAuthorities"
    , "CalledUpShareCapitalNotPaid"
    , "ExpenditureAuthorisationsAndLettersOfCredit"
    , "GlobalTaxDeferred"
    , "GlobalTaxRefund"
    , "InternalTransfers"
    , "OtherConsumables"
    , "ProvisionsCurrentAssets"
    , "ShortTermInvestmentsInRelatedParties"
    , "ShortTermLoansAndAdvancesToRelatedParties"
    , "TradeAndOtherReceivables"
  ],
  "Fixed Asset": [
    "AccumulatedDepletion",
    "AccumulatedDepreciation",
    "DepletableAssets",
    "FixedAssetComputers",
    "FixedAssetCopiers",
    "FixedAssetFurniture",
    "FixedAssetPhone",
    "FixedAssetPhotoVideo",
    "FixedAssetSoftware",
    "FixedAssetOtherToolsEquipment",
    "FurnitureAndFixtures",
    "Land",
    "LeaseholdImprovements",
    "OtherFixedAssets",
    "AccumulatedAmortization",
    "Buildings",
    "IntangibleAssets",
    "MachineryAndEquipment",
    "Vehicles",
    "AssetsInCourseOfConstruction",
    "CapitalWip",
    "CumulativeDepreciationOnIntangibleAssets",
    "IntangibleAssetsUnderDevelopment",
    "LandAsset",
    "NonCurrentAssets",
    "ParticipatingInterests",
    "ProvisionsFixedAssets",
  ],
  "Other Asset": [
    "LeaseBuyout",
    "OtherLongTermAssets",
    "SecurityDeposits",
    "AccumulatedAmortizationOfOtherAssets",
    "Goodwill",
    "Licenses",
    "OrganizationalCosts",
    "Available with minor version: 13",
    "AssetsHeldForSale",
    "AvailableForSaleFinancialAssets",
    "DeferredTax",
    "Investments",
    "LongTermInvestments",
    "LongTermLoansAndAdvancesToRelatedParties",
    "OtherIntangibleAssets",
    "OtherLongTermInvestments",
    "OtherLongTermLoansAndAdvances",
    "PrepaymentsAndAccruedIncome",
    "ProvisionsNonCurrentAssets",
  ],
  "Accounts Receivable": ["Accounts Receivable"],
  "Equity": [
    "OpeningBalanceEquity",
    "PartnersEquity",
    "RetainedEarnings",
    "AccumulatedAdjustment",
    "OwnersEquity",
    "PaidInCapitalOrSurplus",
    "​PartnerContributions",
    "PartnerDistributions",
    "PreferredStock",
    "CommonStock",
    "TreasuryStock",
    "EstimatedTaxes",
    "Healthcare",
    "PersonalIncome",
    "PersonalExpense",
    "Available with minor version: 13",
    "AccumulatedOtherComprehensiveIncome",
    "CalledUpShareCapital",
    "CapitalReserves",
    "DividendDisbursed",
    "EquityInEarningsOfSubsiduaries",
    "InvestmentGrants",
    "MoneyReceivedAgainstShareWarrants",
    "OtherFreeReserves",
    "ShareApplicationMoneyPendingAllotment",
    "ShareCapital",
    "Funds",
  ],
  "Expense": [
    "OpeningBalanceEquity",
    "PartnersEquity",
    "RetainedEarnings",
    "AdvertisingPromotional",
    "BadDebts",
    "BankCharges",
    "CharitableContributions",
    "CommissionsAndFees",
    "Entertainment",
    "EntertainmentMeals",
    "EquipmentRental",
    "FinanceCosts",
    "GlobalTaxExpense",
    "Insurance",
    "InterestPaid",
    "LegalProfessionalFees",
    "OfficeExpenses",
    "OfficeGeneralAdministrativeExpenses",
    "OtherBusinessExpenses",
    "OtherMiscellaneousServiceCost",
    "PromotionalMeals",
    "RentOrLeaseOfBuildings",
    "RepairMaintenance",
    "ShippingFreightDelivery",
    "SuppliesMaterials",
    "Travel",
    "TravelMeals",
    "Utilities",
    "Auto",
    "CostOfLabor",
    "DuesSubscriptions",
    "PayrollExpenses",
    "TaxesPaid",
    "UnappliedCashBillPaymentExpense",
    "Utilities",
    "Available with minor version: 13",
    "AmortizationExpense",
    "AppropriationsToDepreciation",
    "BorrowingCost",
    "CommissionsAndFees",
    "DistributionCosts",
    "ExternalServices",
    "ExtraordinaryCharges",
    "IncomeTaxExpense",
    "LossOnDiscontinuedOperationsNetOfTax",
    "ManagementCompensation",
    "OtherCurrentOperatingCharges",
    "OtherExternalServices",
    "OtherRentalCosts",
    "OtherSellingExpenses",
    "ProjectStudiesSurveysAssessments",
    "PurchasesRebates",
    "ShippingAndDeliveryExpense",
    "StaffCosts",
    "Sundry",
    "TravelExpensesGeneralAndAdminExpenses",
    "TravelExpensesSellingExpense",
  ],
  "Other Expense": [
    "Depreciation",
    "ExchangeGainOrLoss",
    "OtherMiscellaneousExpense",
    "PenaltiesSettlements",
    "Amortization",
    "GasAndFuel",
    "HomeOffice",
    "HomeOwnerRentalInsurance",
    "OtherHomeOfficeExpenses",
    "MortgageInterest",
    "RentAndLease",
    "RepairsAndMaintenance",
    "ParkingAndTolls",
    "Vehicle",
    "VehicleInsurance",
    "VehicleLease",
    "VehicleLoanInterest",
    "VehicleLoan",
    "VehicleRegistration",
    "VehicleRepairs",
    "OtherVehicleExpenses",
    "Utilities",
    "WashAndRoadServices",
    "DeferredTaxExpense",
    "Depletion",
    "ExceptionalItems",
    "ExtraordinaryItems",
    "IncomeTaxOtherExpense",
    "MatCredit",
    "PriorPeriodItems",
    "TaxRoundoffGainOrLoss",
  ],
  "Cost of Goods Sold": [
    "EquipmentRentalCos",
    "OtherCostsOfServiceCos",
    "ShippingFreightDeliveryCos",
    "SuppliesMaterialsCogs",
    "CostOfLaborCos",
    "CostOfSales",
    "FreightAndDeliveryCost",
  ],
  "Accounts Payable": [
    "Accounts Payable",
    "OutstandingDuesMicroSmallEnterprise",
    "OutstandingDuesOtherThanMicroSmallEnterprise"
  ]
  ,
  "Credit Card": [
    "Credit Card"
  ],
  "Long Term Liability": [
    "NotesPayable",
    "OtherLongTermLiabilities",
    "ShareholderNotesPayable",
    "AccrualsAndDeferredIncome",
    "AccruedLongLermLiabilities",
    "AccruedVacationPayable",
    "BankLoans",
    "DebtsRelatedToParticipatingInterests",
    "DeferredTaxLiabilities",
    "GovernmentAndOtherPublicAuthorities",
    "GroupAndAssociates",
    "LiabilitiesRelatedToAssetsHeldForSale",
    "LongTermBorrowings",
    "LongTermDebit",
    "LongTermEmployeeBenefitObligations",
    "ObligationsUnderFinanceLeases",
    "OtherLongTermProvisions",
    "ProvisionForLiabilities",
    "ProvisionsNonCurrentLiabilities",
    "StaffAndRelatedLongTermLiabilityAccounts",
  ],
  "Other Current Liability": [
    "DirectDepositPayable",
    "LineOfCredit",
    "LoanPayable",
    "GlobalTaxPayable",
    "GlobalTaxSuspense",
    "OtherCurrentLiabilities",
    "PayrollClearing",
    "PayrollTaxPayable",
    "PrepaidExpensesPayable",
    "RentsInTrustLiability",
    "TrustAccountsLiabilities",
    "FederalIncomeTaxPayable",
    "InsurancePayable",
    "SalesTaxPayable",
    "StateLocalIncomeTaxPayable",
    "AccruedLiabilities",
    "CurrentLiabilities",
    "CurrentPortionEmployeeBenefitsObligations",
    "CurrentPortionOfObligationsUnderFinanceLeases",
    "CurrentTaxLiability",
    "DividendsPayable",
    "DutiesAndTaxes",
    "InterestPayables",
    "ProvisionForWarrantyObligations",
    "ProvisionsCurrentLiabilities",
    "ShortTermBorrowings",
    "SocialSecurityAgencies",
    "StaffAndRelatedLiabilityAccounts",
    "SundryDebtorsAndCreditors",
    "TradeAndOtherPayables",
  ],
  "Income": [
    "NonProfitIncome",
    "OtherPrimaryIncome",
    "SalesOfProductIncome",
    "ServiceFeeIncome",
    "DiscountsRefundsGiven",
    "UnappliedCashPaymentIncome",
    "CashReceiptIncome",
    "OperatingGrants",
    "OtherCurrentOperatingIncome",
    "OwnWorkCapitalized",
    "RevenueGeneral",
    "SalesRetail",
    "SalesWholesale",
    "SavingsByTaxScheme",
  ],
  "Other Income": [
    "DividendIncome",
    "InterestEarned",
    "OtherInvestmentIncome",
    "OtherMiscellaneousIncome",
    "TaxExemptInterest",
    "GainLossOnSaleOfFixedAssets",
    "GainLossOnSaleOfInvestments",
    "LossOnDisposalOfAssets",
    "OtherOperatingIncome",
    "UnrealisedLossOnSecuritiesNetOfTax",
  ]
}
